# neoforge.mods.toml for the Friend Finder mod
# TOML format reference: https://github.com/toml-lang/toml

modLoader="javafml" #mandatory
loaderVersion="[1,)" #mandatory
license="MIT"

# Fill this in if you have a repo issue tracker (recommended before publishing)
#issueTrackerURL="https://github.com/Martear09/friendfinder/issues" #optional

[[mods]] #mandatory
modId="friendfinder" #mandatory
version="1.0.1" #mandatory
displayName="Friend Finder" #mandatory

# If you have a homepage/repo, uncomment and fill in:
#displayURL="https://github.com/Martear09/friendfinder" #optional

# If you add a logo image to the mod's resources, put its filename here:
#logoFile="friendfinder.png" #optional

authors="Martear09"

description='''
Adds the Friend Finder item.
'''

[[dependencies.friendfinder]]
modId="neoforge"
type="required"
versionRange="[21.1.235,)"
ordering="NONE"
side="BOTH"

[[dependencies.friendfinder]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"