
modLoader="javafml"
loaderVersion="[1,)"
license="MIT"

[[mods]]
modId="friendfinder"
version="1.0.1"
displayName="Friend Finder"

displayURL="https://github.com/Martear09/NeoForge-FriendFinder"


logoFile="friendfinderlogo.png"

authors="Martear09"

description='''
Adds the Friend Finder item.
'''

[[dependencies.friendfinder]]
modId="neoforge"
type="required"
versionRange="[21.1.235,)"
ordering="NONE"
side="BOTH"

[[dependencies.friendfinder]]
modId="minecraft"
type="required"
versionRange="[1.21.1]"
ordering="NONE"
side="BOTH"